export const SET_USER_LOCATION = "SET_USER_LOCATION";
export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SEARCH_TEXT_CHANGE = "SEARCH_TEXT_CHANGE";
export const SET_COORDS_FOR_LOOKING_CITY = "SET_COORDS_FOR_LOOKING_CITY";
