export const SHOW_LOADER = "SHOW_LOADER";
export const HIDE_LOADER = "HIDE_LOADER";
export const SEARCH_TEXT_CHANGE = "SEARCH_TEXT_CHANGE";
export const SET_COORDS_FOR_CITY = "SET_COORDS_FOR_CITY";
export const SET_WEATHER_INFO = "SET_WEATHER_INFO";
